### ISSUE TITLE
Build issue?

### ISSUE THREAD

**Issue by molikd** [hyperspike/hyperctl#5]
When I try to build hyperctl I get an non-zero exit error:

```bash
 11:52:33 dmolik@Davids-MacBook-Pro.local {~/OneDrive - nd.edu/Code}$  docker build - < Dockerfile
Sending build context to Docker daemon   2.56kB
Step 1/9 : FROM golang:1.15.6-alpine3.12 AS build
1.15.6-alpine3.12: Pulling from library/golang
801bfaa63ef2: Pull complete 
ee0a1ba97153: Pull complete 
1db7f31c0ee6: Pull complete 
ecebeec079cf: Pull complete 
63b48972323a: Pull complete 
Digest: sha256:49b4eac11640066bc72c74b70202478b7d431c7d8918e0973d6e4aeb8b3129d2
Status: Downloaded newer image for golang:1.15.6-alpine3.12
 ---> 1463476d8605
Step 2/9 : COPY ./ $GOPATH/src/hyperspike/hyperctl
 ---> 79159f1acf6d
Step 3/9 : ARG VERSION
 ---> Running in 102636fa2583
Removing intermediate container 102636fa2583
 ---> b02aaecf4f3d
Step 4/9 : RUN apk --no-cache add make binutils 	&& cd $GOPATH/src/hyperspike/hyperctl 	&& make VERSION=${VERSION} install
 ---> Running in a8bf4f953c03
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libgcc (9.3.0-r2)
(2/4) Installing libstdc++ (9.3.0-r2)
(3/4) Installing binutils (2.34-r1)
(4/4) Installing make (4.3-r0)
Executing busybox-1.31.1-r19.trigger
OK: 17 MiB in 19 packages
make: *** No rule to make target 'install'.  Stop.
The command '/bin/sh -c apk --no-cache add make binutils 	&& cd $GOPATH/src/hyperspike/hyperctl 	&& make VERSION=${VERSION} install' returned a non-zero code: 2
```

Is this the intended behavior?

**Comment by dmolik** [comment]
I'm not sure what's going on with your redirect.

However, I suggest either running `make container` or avoiding the redirect and running `docker build .` .

**Comment by dmolik** [comment]
Where you able to get it to build?

Are you happy with the `make` rules?

**Comment by molikd** [comment]
testing later today.

**Comment by molikd** [comment]
Container build now working well. 

however, OSX install of bin errors:

make install local
CGO_ENABLED=0  go build -v -ldflags "-s -w -X hyperspike.io/hyperctl.Version=ccfd95e" -o hyperctl ./cmd/
install -s -m 0755 -v hyperctl /usr/bin/hyperctl
install: /usr/bin/hyperctl: Operation not permitted
make: *** [install] Error 71

sudo should fix, but if default install path is /usr/local/bin no problems will be encountered

**Comment by dmolik** [comment]
the target is actually `make install_local' with an underscore

**Comment by molikd** [comment]
weird that errors out for me and tries to install in miniconda:

```
install: child process failed: xcrun strip - /Users/dmolik/miniconda3/bin/hyperctl
make: *** [Makefile:22: install_local] Error 70
```

make works fine though, so it's probably a bin/path problem.

**Comment by dmolik** [comment]
This is an issue with the install command on Mac, as apparently it doesn't properly support stripping.

**Comment by molikd** [comment]
Yeah I'm too worried about it, the workaround is to compile and then move the bin into your path somewhere.
